services:
    rsshub:
        build: .
        ports:
            - '1200:1200'
        env_file: .env
        depends_on:
            redis:
                condition: service_healthy
        restart: unless-stopped

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
        ports:
            - '6379:6379'
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s

volumes:
    redis-data:
